chore: upgrade AWS ECR scanning type

diff --git a/.github/actions/build/action.yml b/.github/actions/build/action.yml
--- a/.github/actions/build/action.yml
+++ b/.github/actions/build/action.yml
@@ -1,7 +1,11 @@
 ---
 #------------------------------------------------------------------------------
-# - build the Docker image
+# - build and push the Docker image to AWS ECR
 # - run all unit tests
+#
+# Updates:
+# - Nov-2025: added step to upgrade ECR Basic Scanning to new version
+#   [Action Required] Upgrade to new version of ECR Basic Scanning before February 2, 2026 [AWS Account: 090511222473]
 #------------------------------------------------------------------------------
 name: Build
 branding:
@@ -65,6 +69,24 @@ runs:
         echo "-------------"
         aws sts get-caller-identity
 
+    # Upgrade ECR Basic Scanning to new version (required before Feb 2, 2026)
+    - name: Upgrade ECR Basic Scanning
+      id: upgrade-ecr-scanning
+      shell: bash
+      run: |-
+        echo "Checking current ECR scanning version:"
+        echo "-------------------------------------"
+        current_setting=$(aws ecr get-account-setting --name BASIC_SCAN_TYPE_VERSION --query 'value' --output text 2>/dev/null || echo "CLAIR")
+        echo "Current setting: $current_setting"
+
+        if [ "$current_setting" != "AWS_NATIVE" ]; then
+          echo "Upgrading to AWS_NATIVE scanning..."
+          aws ecr put-account-setting --name BASIC_SCAN_TYPE_VERSION --value AWS_NATIVE
+          echo "ECR scanning upgraded to AWS_NATIVE"
+        else
+          echo "ECR scanning already using AWS_NATIVE version"
+        fi
+
     # NOTE: we're going to borrow the SMTP credentials from the Kubernetes secret
     # for this environment, since unit tests will send a test email and we don't
     # have a default set of credentials for the local environment.
@@ -114,3 +136,13 @@ runs:
         cache-to: type=gha,mode=max
       env:
         ENVIRONMENT: ${{ inputs.environment }}
+
+    # Nov-2025: ECR image scanning upgrade
+    # Trigger new image scan after upgrading ECR scanning version
+    - name: Trigger ECR image scan
+      id: trigger-scan
+      shell: bash
+      run: |-
+        echo "Triggering new image scan for latest tag..."
+        aws ecr start-image-scan --repository-name ${{ env.AWS_ECR_REPO }} --image-id imageTag=latest || echo "Scan already in progress or failed"
+        echo "ECR image scan triggered"
